version: "3.8"

services:
    backend:
        image: php:7.4-cli
        working_dir: /usr/src/app
        command: php -S localhost:8080
        volumes:
            - ./app:/usr/src/app
        ports: 
            - 8080:8080
        